import pandas as pd
import oracledb

df = pd.read_csv("sentiment_reviews.csv")

connection = oracledb.connect(user="admin", password="password", dsn="localhost/XEPDB1")
cursor = connection.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS reviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    bank VARCHAR2(50),
    review CLOB,
    rating NUMBER,
    review_date DATE,
    sentiment VARCHAR2(10),
    sentiment_score FLOAT,
    source VARCHAR2(50),
    PRIMARY KEY (id)
)
""")

for _, row in df.iterrows():
    cursor.execute("""
        INSERT INTO reviews (bank, review, rating, review_date, sentiment, sentiment_score, source)
        VALUES (:1, :2, :3, TO_DATE(:4, 'YYYY-MM-DD'), :5, :6, :7)
    """, (row['bank'], row['review'], row['rating'], str(row['date']),
          row['sentiment'], row['sentiment_score'], row['source']))

connection.commit()
cursor.close()
connection.close()
